### ISSUE TITLE
Provide client version info programatically

### ISSUE THREAD

**Issue by bennydiamond** [Azure/iot-hub-device-update#141]
This is more of a feature request.

Provide string to populate field [ "AduVer" in DeviceTwin](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-plug-and-play) programmatically with release version/git hash.

**Comment by jw-msft** [comment]
yes, putting git commit in the twin could be useful to ensure agents are the same across device twins. Did you have a particular use case for it, or would just find it useful during twin inspection?

There could be an option to use the short commit hash vs. full commit hash since max twin size is constrained ([32KB if I'm reading this correctly](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-size)). Any preference?

Ideally, it would need to be done in such a way as to avoid unnecessary cmake reconfigures and/or minimal code rebuilding and stay in sync when new commits are made. There are various ways each with its own tradeoffs.

**Comment by bennydiamond** [comment]
adu_core_interface agent [already populates field `aduVer`](https://github.com/Azure/iot-hub-device-update/blob/2cd165ba05cf7a6eff34cbf6c26e4ae30cc9d5d9/src/agent/adu_core_interface/src/device_properties.c#L141) in device twin. To successfully compile, user must supply string for preprocessor define `ADUC_VERSION`.

I think `ADUC_VERSION` should be defined internally. Same goes for `ADUC_BUILDER_IDENTIFIER`.

**Comment by esha0611** [comment]
The ADUC_Version and the ADUC_Build identifier is set in the top-level [CMakeLists.txt](https://github.com/Azure/iot-hub-device-update/blob/main/CMakeLists.txt) before building. Refer to How To Build the Device Update Agent(https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md).

**Comment by bennydiamond** [comment]
> The ADUC_Version and the ADUC_Build identifier is set in the top-level [CMakeLists.txt](https://github.com/Azure/iot-hub-device-update/blob/main/CMakeLists.txt) before building. Refer to How To Build the Device Update Agent(https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-build-agent-code.md).

Gotcha. I did not see that as our project's build process does not make use of cmake.
Personally, I think it would be more useful to have these defined in the code. It would certainly help in the situation I'm in :P 

It could still be implemented as it is right now, just offer the possibility of using a default value.

For example, in whatever header file (version.h maybe?):
```
#ifndef ADUC_VERSION_MAJOR
#define ADUC_VERSION_MAJOR "0"
#endif /* ADUC_VERSION_MAJOR */

#ifndef ADUC_VERSION_MINOR
#define ADUC_VERSION_MINOR "0"
#endif /* ADUC_VERSION_MINOR */

#ifndef ADUC_VERSION_PATCH
#define ADUC_VERSION_PATCH "0"
#endif /* ADUC_VERSION_PATCH */

#ifndef ADUC_VERSION
#define ADUC_VERSION ADUC_VERSION_MAJOR "." ADUC_VERSION_MINOR "." ADUC_VERSION_PATCH
#endif /* ADUC_VERSION */
```

**Comment by eshashah-msft** [comment]
@bennydiamond, we are not planning any action at this time on this.
