### ISSUE TITLE
Failed to set DO connection string in Nested Edge scenario, result: 0 [StartupAgent]

### ISSUE THREAD

**Issue by Christian-e-S** [Azure/iot-hub-device-update#209]
I get this error when I build and run according to the documentation, using a connection string provided by Azure Identity Service.  
(by setting "connectionType": "AIS" in /etc/adu/du-config.json)

I took me a while to understand what's going on, and the solution was quite simple:

The function "deliveryoptimization_set_iot_connection_string" tries to store the received connection string to this location "/etc/deliveryoptimization-agent/sdk-config.json". 

When the directory "/etc/deliveryoptimization-agent" doesn't exists, you get this error.  

I think, it might make sense to create that directory as part of the installation process.

**Comment by jw-msft** [comment]
That directory is already created by DO debian package postinst maintainer script (see below).

One possible improvement could be to add this to a runtime healthcheck check in DO agent code (it would belong in microsoft/do-client because docs_svc_config_dir_path is a compile-time option when CMake generates the build file, so could be different depending on if this was customized).

If not using debian pkg and feel strongly about it, then I suggest opening a github issue on microsoft/do-client repo.

## From microsoft/do-client repo:

https://github.com/microsoft/do-client/blob/21d94248eb13a3644c948a264b7d649addcc7851/CMakeLists.txt#L123
```sh
    set(DOSVC_BIN_NAME "deliveryoptimization-agent")
```
https://github.com/microsoft/do-client/blob/504832cd0d381cbb3b741c4f08454088b13f4489/client-lite/CMakeLists.txt#L78
```
    set(docs_svc_config_dir_path "/etc/${DOSVC_BIN_NAME}")
```
https://github.com/microsoft/do-client/blob/a4d5bd8f33e9edc9a3891fc29684884c450dd80c/client-lite/build/postinst.in.sh#L8
`config_path=@docs_svc_config_dir_path@`

https://github.com/microsoft/do-client/blob/a4d5bd8f33e9edc9a3891fc29684884c450dd80c/client-lite/build/postinst.in.sh#L53
```sh
configure_dir() {
    local dir_path="$1"
    echo "Configuring dir: $dir_path"
    if [ ! -d "$dir_path" ]; then
        mkdir "$dir_path"
    fi
    chgrp -R $do_group_name "$dir_path"
    chown $do_user_name "$dir_path"
}

configure_dir "$config_path"
```

**Comment by eshashah-msft** [comment]
@Christian-e-S closing this issue per Jeff's response. Please create an issue on microsoft/do-client repo if required.
