### ISSUE TITLE
Import update from bash

### ISSUE THREAD

**Issue by strowk** [Azure/iot-hub-device-update#26]
I need to import image to update the device from Ubuntu, but this guide - https://docs.microsoft.com/en-us/azure/iot-hub-device-update/import-update requires to use Powershell. Please provide guide for bash as well.

**Comment by andrewbrownmsft** [comment]
Hi,

Thanks for the feedback - we really appreciate you taking the time to help us improve Device Update for IoT Hub!

Can you provide some additional details about what you'd want from the bash option? Are you looking for something that enables you to try out Device Update more quickly, or is this for longer-term use (such as integration with existing tools that you already have)? If it is just to quickly try out Device Update, would a sample import manifest and update file be a good alternative instead of having to use PowerShell?

Some of the things the PowerShell script does may not be easily possible via bash; if we were not able to include the full functionality via bash, would you prefer to download and install node.js or Python as an alternative to PowerShell, or are you mostly looking to avoid downloading anything you aren't already using?

Also, if for some reason you can't use PowerShell at all and needed to create an import manifest, a workaround is to copy the sample file on the [Import How-To Guide page,](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/import-update#review-generated-import-manifest) and modify the values as needed using the guidance on the [Import Schema page](https://docs.microsoft.com/en-us/azure/iot-hub-device-update/import-schema). If you end up doing that and encounter any problems, please do let us know.

**Comment by Voxel07** [comment]
I want to avoid downloading additional software.
So I wrote a Bash script that generates the Manifest for me, the only thing missing is the sha256 to Base64 conversion. @andrewbrownmsft is there a way to do this in bash? The only ways I found where PowerShell, C# and Python.

**Comment by strowk** [comment]
@Voxel07 , this tool - https://linux.die.net/man/1/base64 usually is available in linux. Will that work? Just pipe whatever you want to make encode in there..

**Comment by andrewbrownmsft** [comment]
Thanks, folks, this is good feedback. Based on this, we are now planning on having a bash option in our next release (TBD timeframe, I'll post back when we have a date).

In the meantime, a suggestion from someone on the team is to try this for the sha256 to Base64 conversion from bash:

openssl dgst -sha256 -binary BlueScreens.zip | openssl base64

/mnt/c/temp
16:13:36 ❯ openssl dgst -sha256 -binary BlueScreens.zip | openssl base64
31UR3PLVOWBn3Uz0NrtHgPQWPI45oYWCXey8bWens/c=

**Comment by andrewbrownmsft** [comment]
Hi folks,

Sorry for the delay - we now have the bash script available here: 

https://github.com/Azure/iot-hub-device-update/tree/release/2021-q2/tools/AduCmdlets

If you find any issues, please do let us know!
