### ISSUE TITLE
Device not listed during deployment

### ISSUE THREAD

**Issue by ccli8** [Azure/iot-hub-device-update#421]
I am porting 1.0.2 to my device. This port has reduced to meet my resource-constrained environment and has the following characteristics:
- Cortex-M4 based chip
- Mbed OS 6
- MCUboot for update handler
- No Diagnostics
- No file system/shared object

On Azure Portal, I've done with:
-   [Create Device Update for IoT Hub resources](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/create-device-update-account?tabs=portal)

- [Configure access control roles for Device Update resources](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/configure-access-control-device-update?tabs=portal)

IoT Hub Data Contributor:

![IoT Hub Data Contributor](https://user-images.githubusercontent.com/15923441/223627181-5cf8aa64-3cdc-44f5-8743-91019634df85.png)

Device Update Administrator:

![Device Update Administrator](https://user-images.githubusercontent.com/15923441/223627401-df566b65-2d4f-41ce-a491-2258af8ae3be.png)

After import update, I try to deploy to the device. In **Default Group**, I can see my device listed:

![Default Group](https://user-images.githubusercontent.com/15923441/223628053-88f68b25-1ca1-4a1f-bff9-b408c639cacf.png)

But in Deployment tab, I cannot see my device listed:

![image](https://user-images.githubusercontent.com/15923441/223639924-d7b16f34-45cf-4f3e-924c-bb8316cc65a3.png)

According to device console log, deployment actually has started:
[device_console_log.txt](https://github.com/Azure/iot-hub-device-update/files/10917985/device_console_log.txt)

```
Info: ComponentName:deviceUpdate, propertyName:service
Info: Update Action info string ({"workflow":{"action":3.00000000000000000,"id":"e385cf9f-f2f4-460b-b635-c0ddebf88ffa"},"updateManifest":"{\"manifestVersion\":\"5\",\"updateId\":{\"provider\":\"Nuvoton\",\"name\":\"NuMaker-ADU-Sample-Update\",\"version\":\"1.0.7\"},\"compatibility\":[{\"manufacturer\":\"Nuvoton\",\"model\":\"NuMaker-ADU-Sample-Device\"}],\"instructions\":{\"steps\":[{\"handler\":\"nuvoton\/mcubupdate:1\",\"files\":[\"f3c0f3866f41375ec\"],\"handlerProperties\":{\"installedCriteria\":\"1.0.7\"}}]},\"files\":{\"f3c0f3866f41375ec\":{\"fileName\":\"NuMaker-mbed-Azure-IoT-CSDK-OTA-example_V1.0.7_signed.bin\",\"sizeInBytes\":629600,\"hashes\":{\"sha256\":\"1iCPEvtXOjAzFShxq+i284AE2VnG74BHbQjsM4l2DKA=\"}}},\"createdDateTime\":\"2023-03-08T05:13:04Z\"}","updateManifestSignature":null,"fileUrls":null}), property version (39)
Info: cancellationType(0) => None
Info: Calling IsInstalledCallback to check if content is installed.
Info: IsInstalledCallback called
```

The device twin also reflects this:
[device_twen.txt](https://github.com/Azure/iot-hub-device-update/files/10917989/device_twen.txt)

```
            "deviceUpdate": {
                "__t": "c",
                "agent": {
                    "deviceProperties": {
                        "manufacturer": "Nuvoton",
                        "model": "NuMaker-ADU-Sample-Device",
                        "contractModelId": "dtmi:azure:iot:deviceUpdateContractModel;2"
                    },
                    "compatPropertyNames": "manufacturer,model",
                    "lastInstallResult": {
                        "resultCode": 400,
                        "extendedResultCode": 0,
                        "resultDetails": ""
                    },
                    "state": 6,
                    "workflow": {
                        "action": 3,
                        "id": "e385cf9f-f2f4-460b-b635-c0ddebf88ffa"
                    },
                    "installedUpdateId": "{\"provider\":\"Nuvoton\",\"name\":\"NuMaker-ADU-Sample-Update\",\"version\":\"1.0.5\"}"
                },
```

**Comment by josephmsft** [comment]
Can you confirm version 1.0.7 of the update is not deleted? It appears that the code to process the state change of the agent into "InProgress" which would have made the agent show up in the deployment thought the state change was invalid because it didn't find the update.

If you delete this deployment and try deploying 1.0.7 again does the issue happen again?

**Comment by ccli8** [comment]
I confirm the 1.0.7 update remains there  I can delete the deployment and re-deploy repeatedly, but the issue still happens.

Besides, my IoT Hub is located at East Asia and Device Update at Southeast Asia. Does it matter?

**Comment by ccli8** [comment]
> Besides, my IoT Hub is located at East Asia and Device Update at Southeast Asia. Does it matter?

I change both IoT Hub and Device Update regions to East US, but the issue remains. So region is not the cause.

**Comment by josephmsft** [comment]
Yeah the region shouldn't matter. I am investigating some other issues right now but will get back to this investigation when I finish them.

**Comment by josephmsft** [comment]
If you re-import 1.0.7 with a higher version (say 1.0.8) do you see the same behavior when deploying the higher version?

**Comment by jw-msft** [comment]
From your agent logs, it seems not be patching twin with new Idle state and there seems to be bad magic number on the scratch partition. Is the main issue lack of reporting of successful deployment (transition to Idle state from Apply state), or that it reported failed state?

- After apply succeeded and going to Idle state, I did not see it report Idle state and post it to the twin _AND_ I saw the following error traced in the _patched_ code:

```
Error: Time:Wed Mar  8 6:49:51 2023
 File:.\mbed-client-for-azure\mbed\COMPONENT_AZIOT_OTA\iot-hub-device-update_patch\adu_workflow\agent_workflow.cpp Func:ADUC_Workflow_AutoTransitionWorkflow Line:802 Invalid workflow step 0
```

- Also, not sure if this is an issue with updated partition that will be booted into, but magic number of the scratch partition is **bad**:

```[INFO][MCUb]: Scratch: magic=bad, swap_type=0x1, copy_done=0x2, image_ok=0x2```

Extended Log snippet here:

```
Info: Calling ADUC_RebootSystem
Info: ADUC_RebootSystem called. Rebooting system.
Info: WorkCompletionCallback: Apply succeeded. Going to state Idle
Info: Setting UpdateState to Idle
Info: Sandbox root path not set. Use default: '/var/lib/adu/downloads'
Info: UpdateAction: Idle. Ending workflow with WorkflowId: e385cf9f-f2f4-460b-b635-c0ddebf88ffa
Info: Calling SandboxDestroyCallback
Info: {e385cf9f-f2f4-460b-b635-c0ddebf88ffa} Deleting dummy sandbox: /var/lib/adu/downloads/e385cf9f-f2f4-460b-b635-c0ddebf88ffa
Info: Calling IdleCallback
Info: Now idle. workflowId: e385cf9f-f2f4-460b-b635-c0ddebf88ffa
Info: clearing when no active workflow.
Error: Time:Wed Mar  8 6:49:51 2023
 File:.\mbed-client-for-azure\mbed\COMPONENT_AZIOT_OTA\iot-hub-device-update_patch\adu_workflow\agent_workflow.cpp Func:ADUC_Workflow_AutoTransitionWorkflow Line:802 Invalid workflow step 0
Info: Apply worker thread finished
[INFO][BL]: Starting MCUboot
[INFO][MCUb]: Primary image: magic=good, swap_type=0x2, copy_done=0x1, image_ok=0x1
[INFO][MCUb]: Scratch: magic=bad, swap_type=0x1, copy_done=0x2, image_ok=0x2
```

**Comment by ccli8** [comment]
> If you re-import 1.0.7 with a higher version (say 1.0.8) do you see the same behavior when deploying the higher version?

@josephmsft Yes, device is still not listed in the deployment.

Then another phenomenon: During deployment, the device tries to complete the **Apply** process and reboots, but meets connection broken. The connection broken phenomenon keeps existent even though the device is re-flashed or rebooted again, until the deployment is cancelled or removed through Azure Portal and device twin has updated to `nodeployment`:
```
    "properties": {
        "desired": {
            "deviceUpdate": {
                "service": {
                    "workflow": {
                        "action": 255,
                        "id": "nodeployment"
                    }
                },
                "__t": "c"
            },
```

**Comment by ccli8** [comment]
@jw-msft 
> After apply succeeded and going to Idle state, I did not see it report Idle state and post it to the twin AND I saw the following error traced in the patched code:

> it seems not be patching twin with new Idle state

I am porting based on `1.0.2`. Would you direct me to PR or something else which can help apply the patch?

> Also, not sure if this is an issue with updated partition that will be booted into, but magic number of the scratch partition is bad:

This doesn't harm. MCUboot firmware upgrade process goes smoothly.

**Comment by jw-msft** [comment]
> I am porting based on 1.0.2. Would you direct me to PR or something else which can help apply the patch?

Reporting after apply transition to idle has been working since even before 1.0, which came in on this PR: https://github.com/Azure/iot-hub-device-update/pull/235.

It was mentioned that Diagnostics, file system operations, and dynamic loading of shared object .so libraries were removed. Was anything else removed and/or rewritten such as  state transition or reporting logic?

If so, you just need to make sure that when transitioning to Idle state after Apply Success, you have to call the equivalent of [ADUC_Workflow_SetInstalledUpdateIdAndGoToIdle](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L1096) 

The following is more detailed description of what happens in the unmodified agent that runs on Linux:

The way it works is [ReportStateAndResultAsyncCallback field on workflowData is 
 set to AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/agent/adu_core_interface/src/adu_core_interface.c#L87) and is called [here when state is Idle](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L1132) and transitioning to Unknown state inside of [ADUC_Workflow_WorkCompletionCallback](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L904) when the result of the async operation is successful.

[ADUC_Workflow_TransitionWorkflow](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L792) sets the WorkCompletionCallback so that the worker thread for the async operation (e.g. Apply) will call that when the thread is done doing the work.

In [ADUC_Workflow_AutoTransitionWorkflow](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L730), it will call [AgentOrchestration_IsWorkflowComplete](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L768) and it won't be ADUCITF_WorkflowStep_Undefined yet but will still be Idle.

On Apply success, it will transition to Idle state as can be seen [in the state transition table](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L289).

After it transitions to Idle, it will call [ADUC_Workflow_SetInstalledUpdateIdAndGoToIdle](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L1096) that will call [ReportStateAndResultAsyncCallback](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/adu_workflow/src/agent_workflow.c#L1243) which was set to [AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync](https://github.com/Azure/iot-hub-device-update/blob/2d1f03671d45be1e55b89c940514ffe91b3227e0/src/agent/adu_core_interface/src/adu_core_interface.c#L776) earlier that will report the reporting JSON including installedUpdateId to patch the twin.

**Comment by josephmsft** [comment]
It looks like something is wrong with the install result being reported

[JsonPatchError] OperationType:Replace, path:/azureDeviceUpdateCore/agent/lastInstallResult/resultCode, AffectedObject: Microsoft.Azure.AzureDeviceUpdate.Management.DeviceAbstractionLayerService.Common.AduAgentTwinDocument, ErrorMessage: The value '400' is invalid for target location.

Can you share the current device twin for this device "device-symm-002"?

**Comment by ccli8** [comment]
Repeat the flow and get similar device console log and device twin:

[device_console_log_002.txt](https://github.com/Azure/iot-hub-device-update/files/11338854/device_console_log_002.txt)
[device_twen_002.txt](https://github.com/Azure/iot-hub-device-update/files/11338858/device_twen_002.txt)

**Comment by josephmsft** [comment]
It looks like the 1.0.8 deployment has been fully deleted so I was unable to find anything in storage, but based on the errors in the logs, I would follow up with jw-msft and try to follow his guidance to match expected agent behavior as I think something is being reported in an unexpected way or order from the agent.

**Comment by ccli8** [comment]
Per device console log, **state** and  **resultCode**:are reported two times. The report seems reasonable:
1. Before deployment is started: **state** = 0 (`Idle`) and **resultCode** = 200 (`Idle_Success`)
1. After deployment is started: **state** = 6 (`DeploymentInProgress`) and **resultCode** = 400 (`DeploymentInProgress_Success`)

Then according to previous error comment:
>t appears from service logs that the code to process the state change of the agent into "InProgress" which would have made the agent show up in the deployment thought the state change was invalid because it didn't find the update.

> [JsonPatchError] OperationType:Replace, path:/azureDeviceUpdateCore/agent/lastInstallResult/resultCode, AffectedObject: Microsoft.Azure.AzureDeviceUpdate.Management.DeviceAbstractionLayerService.Common.AduAgentTwinDocument, ErrorMessage: The value '400' is invalid for target location.

As **resultCode**=400 is reported, Device Update service fails to find the corresponding update or deployment. Do you have any hint to tackle the problem, like cloud privilege configuration? I am sure update and deployment remained existent at that time.

**Comment by jw-msft** [comment]
@ccli8, from the twin it shows `"installedUpdateId"` is included when `state` is `6` (deployment in-progress), which is incorrect. `"installedUpdateId"` should only be included when sending "state" of 0 (Idle state) when the update has been confirmed to have been installed/deployed completely and it transitions to Idle. In the code in this repo, it is done here usually:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/adu_workflow/src/agent_workflow.c#L685

One can see this in the debugger when building this repo with debug bits (which is the default for scripts/build.sh), and set a breakpoint on
GetReportingJsonValue 
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/agent/adu_core_interface/inc/aduc/adu_core_interface.h#L104

and/or [AzureDeviceUpdateCoreInterface_ReportStateAndResultAsync](https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/agent/adu_core_interface/inc/aduc/adu_core_interface.h#LL89C6-L89C62)


then one can see that "installedUpdateId" JSON object is only set on final transition to Idle state once the update is determined to be already installed.

Here is the state diagram for the [workflow processing state machine](https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/docs/agent-reference/goal-state-support.md#workflow-processing-state-machine) about where it depicts "Report Idle + installedUpdateId":
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/docs/agent-reference/goal-state-support.md#state-machine-diagram

Code paths that report state 6 "deployment in-progress" and state 255 (deployment failed) do not include a non-NULL `installedUpdateId` argument to [GetReportingJsonValue](https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/agent/adu_core_interface/src/adu_core_interface.c#L508), so that json object will not be added to the reported JSON for patching in the "reported" section of the twin as can be seen here:
https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/agent/adu_core_interface/src/adu_core_interface.c#L643

Excerpt from the twin provided via [device_twen_002.txt](https://github.com/Azure/iot-hub-device-update/files/11338858/device_twen_002.txt) showing that `"state"` is `6` and `"installedUpdateId"` element is erroneously included:

```
            "deviceUpdate": {
                "__t": "c",
                "agent": {
                    "deviceProperties": {
                        "manufacturer": "Nuvoton",
                        "model": "NuMaker-ADU-Sample-Device",
                        "contractModelId": "dtmi:azure:iot:deviceUpdateContractModel;2"
                    },
                    "compatPropertyNames": "manufacturer,model",
                    "lastInstallResult": {
                        "resultCode": 400,
                        "extendedResultCode": 0,
                        "resultDetails": ""
                    },
                    "state": 6,
                    "workflow": {
                        "action": 3,
                        "id": "9434738a-e7b4-4bdb-b4b2-0148c6e18845"
                    },
                    "installedUpdateId": "{\"provider\":\"Nuvoton\",\"name\":\"NuMaker-ADU-Sample-Update\",\"version\":\"1.0.4\"}"
```

**Comment by ccli8** [comment]
@jw-msft What you see on "`installedUpdateId"` in device twin is caused by previous update somehow. It remains there without report like "`installedUpdateId": null`. Actually, according to [device_console_log_002.txt](https://github.com/Azure/iot-hub-device-update/files/11338854/device_console_log_002.txt), no "`installedUpdateId"` is reported:
```
Info: Sending D2C message:
{"deviceUpdate":{"__t":"c","agent":{"lastInstallResult":{"stepResults":null,"resultCode":400.00000000000000000,"extendedResultCode":0.00000000000000000,"resultDetails":""},"state":6.00000000000000000,"workflow":{"action":3.00000000000000000,"id":"9434738a-e7b4-4bdb-b4b2-0148c6e18845"}}}}
```

Anyway, to exclude concern on "`installedUpdateId"`, I create one new device and do fresh update. In this case, there's no "`installedUpdateId"` under `"reported"`/`"deviceUpdate"`/`"agent"` in device twin, but the issue remains.
