### ISSUE TITLE
More info on device update agent metadata

### ISSUE THREAD

**Issue by ravi-mungalpara** [Azure/iot-hub-device-update#427]
Hi there,

I was going through [agent metadata](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-plug-and-play#agent-metadata) info. Here are few question.

- "**resultCode**": In the doc I can see value is 700. What does it means and what are the other possible values ?
- "**extendedResultCode**": In the doc I can see value is 0. What does it means and what are the other possible values ?
- I am assuming in case of successful update need to report value of "**lastInstallResult**" object in the below format. What we need to report in case of failure ? do we have any other case apart from success and failure ? 

<img width="443" alt="Capture" src="https://user-images.githubusercontent.com/68859394/225322544-2ce620c0-ad70-4773-abe2-482e4804999d.PNG">

thanks.

**Comment by josephmsft** [comment]
The lastInstallResult fields are not part of the agent to service protocol, in the sense that the service does not examine these values to determine deployment success. The service determines if a deployment is successful by examining the reported values for installedUpdateId and state. LastInstallResult fields are intended to be used by agent implementers to debug failures. Thus you can choose whatever values you want to report there for your agent implementation. Our reference implementation has chosen some codes, I believe 700 is success. But other implementations can choose other codes if they want. StepResults is used for the proxy updating feature https://learn.microsoft.com/en-us/azure/iot-hub-device-update/components-enumerator.

**Comment by jw-msft** [comment]
@ravi-mungalpara May I ask, are you implementing a custom content handler extension, or a custom agent?  If the former, the [how to implement custom update handler doc](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md) may be helpful.  If the latter, may I ask your goals in doing so (e.g. reducing footprint, porting to an unsupported platform, etc) rather than using the client as-is so that it could be improved to meet your needs?

Feel free to fill out the following github discussions surveys so that we can help target your requirements better such as [Board / Hardware](https://github.com/Azure/iot-hub-device-update/discussions/402)

## Result Code

> "resultCode": In the doc I can see value is 700. What does it means and what are the other possible values ?

700 is [ADUC_Result_Apply_Success](
https://github.com/Azure/iot-hub-device-update/blob/main/src/adu_types/inc/aduc/types/adu_core.h#L248).  It means your update deployment was a success after an Apply step (It does download -> install -> apply and when done transitions to idle).

The result codes that end up in the twin are documented in [docs/agent-reference/device-update-agent-extended-result-codes.md](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/device-update-agent-extended-result-codes.md)

ADUC_Result_Apply_Success is defined [here in the code](
https://github.com/Azure/iot-hub-device-update/blob/main/src/adu_types/inc/aduc/types/adu_core.h#L248).

## Extended Result Code

> "extendedResultCode": In the doc I can see value is 0. What does it means and what are the other possible values ?

An Extended Result Code (ERC) of 0 in this case means there is no extended result code information, which is typical for Success result codes.  Sometimes, additional information can be here even for success result codes.

You can find all the ExtendedResultCodes (ERC) defined and documented in the auto-generated [result.h](https://github.com/Azure/iot-hub-device-update/blob/main/src/inc/aduc/result.h)

You should be able to search any ERC in result.h for the decimal or hexadecimal extended error code from logs, or ERC that is reported in the twin.

result.h is auto-generated from [result_codes.json](https://github.com/Azure/iot-hub-device-update/blob/main/scripts/error_code_generator_defs/result_codes.json).

## Reported status values

> I am assuming in case of successful update need to report value of "lastInstallResult" object in the below format. What we need to report in case of failure ? do we have any other case apart from success and failure ?

It is true that these are not required for the service protocol, but they are useful in troubleshooting or understanding the final status of the update deployment as reported in the twin.  

You can learn more about the agent state machine [here](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/goal-state-support.md#workflow-processing-state-machine) and a [diagram is here](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/goal-state-support.md#state-machine-diagram).

**Comment by jw-msft** [comment]
let us know if that didn't answer the questions.
