### ISSUE TITLE
workflow autotransitions to Download after reboot even though apply was succesfull

### ISSUE THREAD

**Issue by wayne-david** [Azure/iot-hub-device-update#435]
![iot_issue](https://user-images.githubusercontent.com/40905642/227162543-71fcb794-9c14-4ca9-a071-0f7549e85410.PNG)

## Expected Behavior
Workflow is expected to transition to Idle with success status on reboot. Azure IOT Hub status for the device is expected to transition from Inprogress to Successful after device reboots.

## Current Behavior
After successfull Aplly for image update.Device successfully reboots to the new updated partition.However,the uncompleted workflow causes the device to doanload the update and apply to the other root partition.This happens in cyclic manner.IOT hub remains always Iprogress state.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.add meta-azure-device-update to yocto local.conf 
2.build adu-base-image with raspberrypi4 as target machine
3.build adu-update-image with raspberrypi4 as target machine
4.Install adu-base-image on raspberrypi4
5.Provision the update on Azure Iot Hub Update

### Device Information
* Host OS [ Ubuntu 18.04]: 
* Architecture [arm64]: 
* Provisioning Method:
*DU Agent Version [linux; 0.8.2-public-preview]:

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by wayne-david** [comment]
![iot_issue](https://user-images.githubusercontent.com/40905642/227162107-e2a71bbd-16ce-41f2-860e-22fc99593089.PNG)

**Comment by neonsoftware** [comment]
Hi. 

[disclaimer, I am not a maintainer, just a fellow user]

As highlighted in the blue line of your screenshot it seems like it all starts from the 'IsInstalled' returning '901' which means 'no, the expected version "0.0.3" is not installed yet'. Therefore the process continues.

Looking into this aspect, may I ask:
- what is the update handler used (ex. swupdate, script, apt) ?
- in your new version, where is the "0.0.3" written ?
- how does the adu agent know where to go and read the "0.0.3" ?

Have a nice day.

**Comment by jw-msft** [comment]
@wayne-david The disk image in the .swu that you deploy needs to have an updated `/etc/adu-version` that has the new version value that matches the installedCriteria; otherwise, IsInstalled will be considered uninstalled and keep trying.

The swupdate V1 handler code that reads from `/etc/adu-version` is here:
https://github.com/Azure/iot-hub-device-update/blob/main/src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp#L444

On line 452, it will set the result to `ADUC_Result_IsInstalled_Installed` if and only if `version == installedCriteria`

Check your installedCriteria value that is in the import manifest to see if it matches the one in the disk image of the .swu file -- they need to match for the agent to consider it to be installed.

You can use `cpio` to unpack the .swu CPIO archive and then mount the disk image to see what the contents of `/etc/adu-version` is for the .swu update payload that you uploaded.

Here is an example of unpacking the tutorial .swu and seeing the value in /etc/adu-version
```sh
get https://github.com/Azure/iot-hub-device-update/releases/download/1.0.2/Tutorial_RaspberryPi.zip
unzip Tutorial_RaspberryPi.zip
cd Tutorial_RaspberryPi

# List contents of .swu CPIO archive:
cpio -i --list < adu-update-image-raspberrypi3-1.0.2-2.swu

# Unpack the contents of .swu CPIO archive
cpio -i < adu-update-image-raspberrypi3-1.0.2-2.swu

# uncompress ext4 raw disk image
gunzip adu-base-image-raspberrypi3.ext4.gz

# mount it read-only on loopback device, 
sudo mkdir /mnt/rpi3
sudo mount -o loop,ro adu-base-image-raspberrypi3.ext4 /mnt/rpi3
cd /mnt/rpi3

# what version is it?  It should match installedCriteria to be considered "installed"
cat etc/adu-version
```

**Comment by wayne-david** [comment]
@jw-msft Thank you for the help.The installedCriteria was totally the problem.Changed installedCriteria and version to be the same in meta-azure-device-update local.conf file.Didn't work at first so I went brutal and reconfigured the whole build environment,worked as a cham!
