### ISSUE TITLE
A/B firmware update with swupdate handler: end up in update loop

### ISSUE THREAD

**Issue by JanZachmann** [Azure/iot-hub-device-update#460]
## Expected Behavior
We've integrated adu in our yocto embedded linux distribution. If we boot from part A and install the update to part B we reboot and make an update validation on the new part. This validation might fail for some reason (e.g. a mandatory service cannot startup). In that case we don't start adu agent on new partion at all. Instead we reboot and start from A again. Now we expect the device to report a failed update which might be retried from cloud. 

Following the schematics (https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/images/apply-phase.png) our assumption was that adu already recognizes the failed update by finding the old version instead the new opne after leaving "update in progress" phase? But it seems it doesn't: https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp#L461
## Current Behavior
After failed update validation on part B and rebooting to A the adu agent reports the current updateid is not installed which makes the whole procedure start again and again (update loop).
My question is how the adu workflow can cover the case an A/B update (logically) fails after successfully applying the update (flashing to and rebooting from new partition)?

## Steps to Reproduce
1. deploy new linux firmware update
2. boot device from partion A
3. run swupdate steps: download, install, apply
4. boot device from partition B
5. validate update
          5.1 delay start of adu agent
          5.2 check several conditions
          5.3 check fails
6. boot device from partition A again
7. adu agent finds old version and reports ADUC_Result_IsInstalled_NotInstalled instead of reporting failed update
8. adu starts update again 

### Device Information
* Host OS: yocto linux kirkstone
* Architecture: amd64, arm32, arm64 
* Provisioning Method: module provisioning with azure identity service
* DU Agent Version: 1.0.2

## Logs

Do you need logs at all?

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vimeht** [comment]
@jw-msft @eshashah-msft can you take a look at this?

**Comment by jw-msft** [comment]
@JanZachmann It sounds as though swupdate v1 hander is being used, or a content handler based on it. If so, swupdate v2 handler should be used instead because it allows a script update payload to be run to allow customization of Apply() and IsInstalled() logic to handle the scenario mentioned.

The rest of this reply will assume use of swupdate v2 handler, but another option is to modify the existing [swupdate handler code ](https://github.com/Azure/iot-hub-device-update/blob/main/src/extensions/step_handlers/swupdate_handler/src/swupdate_handler.cpp) or [write a custom handler](https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/how-to-implement-custom-update-handler.md).

Note: in the following doc it mentions that swupdate v1 handler type is "a limited example that runs the adu-swupdate.sh script included with the Debian package. It only works on ext4 file system images that conform to ADU Yocto built images.":
https://github.com/Azure/iot-hub-device-update/blob/main/docs/agent-reference/device-update-agent-extensibility-points.md#content-handler-extension-type

Therefore, it is not recommended to use swupdate v1 as-is for production devices. Instead, swupdate v2 handler should be used with appropriate customizations in the script to handle failure scenarios and handleType of "microsoft/swupdate:2" in the manifest.  See [swupdatev2 README.md](https://github.com/Azure/iot-hub-device-update/blob/main/src/extensions/step_handlers/swupdate_handler_v2/README.md) for more details.

For example, in the script function that handles `--action-apply` script switch, one could:

- Set an additional uboot environment variable (via `fw_setenv`) that indicates commit status that would only be set to 1 once:
  -  it successfully boots into the new partition
  - AND it passes all verification checks in the script's handling of `--action-is-installed` (when booted into the new partition)
- Get the `commit` and `rpipart` env vars (using `fw_printenv`) and compare them with the current mount point for root partition

If commit is still 0 AND rpipart matches current mount point, then that would indicate a revert after failed boot (or failed-check of new partition image) condition. In that case, return a negative `resultCode` status (to indicate failure) and define a `extendedResultCode` as JSON written to the filepath passed via the `--resultFile` argument.

If commit is 0 and rpipart does NOT match current mount point, then that would mean it is booting into newly updated partition and commit should be set (via e.g. `fw_setenv commit 1`).

For reference here are:
- The [swupdate v1 handler script](https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/adu-shell/scripts/adu-swupdate.sh) that comes with the agent when installed via debian package

Here is an example swupdate v2 script payload:
https://github.com/Azure/iot-hub-device-update/blob/main/src/extensions/step_handlers/swupdate_handler_v2/tests/testdata/adu-yocto-ab-rootfs-update/payloads/example-a-b-update.sh

For reference, the [uboot] script in adu yocto recipes-bsp (https://github.com/Azure/meta-raspberrypi-adu/blob/main/recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in)

**Comment by JanZachmann** [comment]
Thanks for your advise! It matches more or less the assumptions we had. We also already have the u-boot vars you propose. So we will implement like suggested.

One question is open for me: in order to show the device as failed in cloud (and trigger a retry) we report the negative result code. but what would happen if the device changes to NotInstalled result again, e.g. after a reboot? Is the device then still marked as failed in azure or will it get the update again automatically?

**Comment by JanZachmann** [comment]
Hi @jw-msft 
Meanwhile we successfully implemented a solution. What I don't like about the solution is that we had to patch agent_workflow.c in order to detect if a retry was triggered by fleet operator in cloud. we need to do so because we must explicitly allow another installation in content handler script in retry context (instead of returning the error). it would be easier if we would know in content handler if the reason of an update is a retry. is this already possible and I did oversee something?  
BR
Jan

**Comment by jw-msft** [comment]
Hi @JanZachmann

Glad you got it to work but not an ideal solution for sure.

If it's a retry, core agent calls [workflow_update_retry_deployment()](https://github.com/Azure/iot-hub-device-update/blob/0cea32a7a257ee680121ef06e76e17fbdac73c6f/src/utils/workflow_utils/src/workflow_utils.c#L2976), which sets the cancellation type to ADUC_WorkflowCancellationType_Retry and updates the retry timestamp.

The script/swupdate/swupdatev2 handlers, which are all really just script-based handlers, do not currently pass the cancellation type to the script as a cmd-line argument and there's currently no way for the script to call, say, an API via named-pipe FIFO API on the agent process to get it.

The core agent is already leaking internals too much, so patch/authoring a content handler to call workflow_get_cancellation_type() is not ideal.

Instead, probably what makes most sense is for the core agent to export several environment variables of the form ADUC_WORKFLOW_<workflow property> and then the script can just reference e.g. $ADUC_WORKFLOW_CANCELLATION_TYPE

I'm going to close this issue for now, but I'll following-up after discussing with the team to add this type of behavior for script since we would like to address making the content handler interface not require accessing internal workflow_* functions or internals but to just pass the necessary workflow data as primitive data types to the exported functions on the handler plugins.

**Comment by JanZachmann** [comment]
Hi @jw-msft 

Thanks for confirming. We're really looking forward a content-handler / script only solution. An environment variable would work well for us.

BR
Jan
